; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:my-ai-speaker]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
;lib_extra_dirs =
;	C:/Users/jieny/.platformio/packages/framework-arduinoespressif32/libraries
;lib_deps = jandrassy/ArduinoOTA@^1.1.0

[env:ota]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
upload_speed = 921600
monitor_speed = 115200
upload_protocol = espota
board_build.partitions = min_spiffs.csv
upload_port = 172.18.8.132
upload_flags = --port=3232
; 终端里关掉防火墙 → Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
